name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t user-service:latest ./user-service

      - name: Push Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag user-service:latest YOUR_DOCKER_HUB/user-service:latest
          docker push YOUR_DOCKER_HUB/user-service:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/k8s/user-service.yaml

