version: "3.8"
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

